Repository SOEN490-SportsApp/SportsApp, pull requests merged in 2024-10, with the labels that each got.

#94 GH-92: [ci] Add github workflow to run tests on ClientApp
  .github/workflows/frontend-ci-cd.yml
  ClientApp/package.json
Labels: Task

#95 GH-93: [ci] Add GitHub hook to maintain commit message standard.
  git-hooks/add-hooks.sh
  git-hooks/commit-msg
Labels: pull request

#100 GH-99: [feat] Added esLint to clientApp
  ClientApp/.eslintrc.json
  ClientApp/app/_layout.tsx
  ClientApp/app/index.tsx
  ClientApp/package-lock.json
  ClientApp/package.json
  ClientApp/tsconfig.json
Labels: frontend, pull request
