Repository SOEN490-SportsApp/SportsApp, pull requests merged in 2024-11, with the labels that each got.

#113 account registration page
  ClientApp/__tests__/auth/register.test.tsx
  ClientApp/app/_layout.tsx
  ClientApp/app/auth/login.tsx
  ClientApp/app/auth/register.tsx
  ClientApp/app/index.tsx
  ClientApp/assets/images/partial-react-logo.png
  ClientApp/babel.config.js
  ClientApp/components/AuthenticationDivider.tsx
  ClientApp/components/Collapsible.tsx
  ClientApp/components/ConfirmButton.tsx
  ClientApp/components/ExternalLink.tsx
  ClientApp/components/HelloWave.tsx
  ClientApp/components/ParallaxScrollView.tsx
  ClientApp/components/ThemedText.tsx
  ClientApp/components/ThemedView.tsx
  ClientApp/components/__tests__/ThemedText-test.tsx
  ClientApp/components/__tests__/__snapshots__/ThemedText-test.tsx.snap
  ClientApp/constants/Colors.ts
  ClientApp/global.css
  ClientApp/hooks/useThemeColor.ts
  ClientApp/metro.config.js
  ClientApp/nativewind-env.d.ts
  ClientApp/package-lock.json
  ClientApp/package.json
  ClientApp/scripts/reset-project.js
  ClientApp/tailwind.config.js
  ClientApp/tsconfig.json
  package-lock.json
Labels: frontend, User Profile, pull request

#115 GH-114: Add Axios Instance with Token Management, Error Handling, and Centralized Alert Utility
  .gitignore
  ClientApp/__mocks__/@react-native-async-storage/async-storage.js
  ClientApp/api/alertUtils.ts
  ClientApp/api/axiosIntance.ts
  ClientApp/components/__tests__/axiosInstance.test.ts
  ClientApp/jestSetup.ts
  ClientApp/package-lock.json
  ClientApp/package.json
  ClientApp/tsconfig.json
Labels: frontend, General Feature, pull request

#129 GH-32: Enhance OAuth2 and Keycloak configurations with dynamic environment variables and fallback support
  Microservices/user-service/src/main/resources/application.properties
Labels: backend, pull request

#132 GH-32: [chore] Add Swagger Support
  Microservices/user-service/build.gradle
  Microservices/user-service/src/main/java/app/sportahub/userservice/config/auth/SecurityConfig.java
  Microservices/user-service/src/main/resources/application.properties
Labels: backend, pull request

#134 GH-32: [fix] Fix AuthControllerTest.java and MongoConfigTest.java con…
  Microservices/user-service/src/test/java/app/sportahub/userservice/UserServiceApplicationTests.java
  Microservices/user-service/src/test/java/app/sportahub/userservice/config/MongoConfigTest.java
  Microservices/user-service/src/test/java/app/sportahub/userservice/controller/AuthControllerTest.java
Labels: backend, pull request

#138 GH-137: [docs] Describing the setting up, building and running of the…
  README.md
Labels: backend, pull request

#141 GH-31: [refactor] Code restructure and improvement
  ClientApp/__tests__/auth/login.test.tsx
  ClientApp/__tests__/auth/registerAccount.test.tsx
  ClientApp/__tests__/auth/registerProfile.test.tsx
  ClientApp/__tests__/profile.test.tsx
  ClientApp/app/(tabs)/_layout.tsx
  ClientApp/app/(tabs)/create/index.tsx
  ClientApp/app/(tabs)/home/index.tsx
  ClientApp/app/(tabs)/profile/index.tsx
  ClientApp/app/(tabs)/settings/index.tsx
  ClientApp/app/_layout.tsx
  ClientApp/app/auth/login.tsx
  ClientApp/app/auth/registerAccount.tsx
  ClientApp/app/auth/registerProfile.tsx
  ClientApp/components/ConfirmButton.tsx
  ClientApp/hooks/useColorScheme.ts
  ClientApp/hooks/useColorScheme.web.ts
  ClientApp/utils/constants/colors.ts
  ClientApp/utils/constants/enums.ts
  ClientApp/utils/constants/supportedSports.ts
  ClientApp/utils/helpers/ageValidation.ts
Labels: frontend, pull request

#144 GH-38: [fix] Fix failing test
  Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Labels: backend, pull request

#159 GH-159: [docs] Update README with Release Demos and Important Files
  README.md
Labels: backend, documentation, pull request

#168 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/event--template.md
Labels: pull request

#169 GH-167: [fix] Confirm password UI binding fix
  ClientApp/app/auth/registerAccount.tsx
Labels: bug, frontend, pull request

#179 GH-179: [docs] Updated readme to include new team member.
  README.md
Labels: documentation, pull request
