Repository SOEN490-SportsApp/SportsApp, pull requests merged in 2025-03, with the labels that each got.

#364 GH-359: [fix] Color selection bug on registration page
  ClientApp/app/editProfile/sportsSkills.tsx
  ClientApp/components/RegisterProfile/RegisterProfileSports.tsx
Labels: frontend

#379 [feat] Add build-args for JAR_FILE in Dockerfile deployment configuration
  .github/workflows/build-deploy-microservices.yaml
Labels: backend, pull request

#387 GH-386: [bug] Fixes for QR UI and event service filtering
  ClientApp/components/QR/QR.tsx
  ClientApp/services/eventService.ts
Labels: bug, frontend

#389 GH-388: [feat] implement app splash screen and logo
  ClientApp/app.json
Labels: frontend, pull request

#391 GH-390: [fix] restrict post creation to only joined users and UI improvement
  ClientApp/app/events/[eventId].tsx
  ClientApp/components/Event/EventPostsTab.tsx
Labels: bug, frontend, Communication, pull request

#394 [hotfix] Add Spring Boot Actuator for enhanced application monitoring
  Microservices/messaging-service/Dockerfile
  Microservices/messaging-service/build.gradle
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/config/SecurityConfig.java
Labels: backend, pull request

#372 [hotfix] 404 getFriends issue
  Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java
  Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Labels: backend, pull request

#404 GH-403: [fix] Posts display access error fix
  ClientApp/utils/api/endpoints.tsx
  ClientApp/utils/api/profileApiClient.ts
Labels: bug, frontend, pull request

#421 GH-416: [fix] Join expired event
  ClientApp/app/(tabs)/create/index.tsx
  ClientApp/app/events/[eventId].tsx
  ClientApp/components/Helper Components/ClosedButtonEventPage.tsx
Labels: frontend, Event Managment, pull request

#422 GH-399: [fix] Refactor text components for events\[eventId].tsx
  ClientApp/app/events/[eventId].tsx
  ClientApp/utils/localization/en.json
  ClientApp/utils/localization/fr.json
Labels: frontend

#429 GH-0: [fix] Fix build with right gradle-wrapper.jar
  Microservices/orchestration-service/gradle/wrapper/gradle-wrapper.jar
Labels: backend, pull request

#441 GH-0: [hotfix] Accidentally modified event service by mistake
  Microservices/event-service/src/main/java/app/sportahub/eventservice/utils/KeycloakJwtAuthenticationConverter.java
Labels: backend, pull request

#440 GH-0: [refactor] Added distance filter to event search endpoint.
  Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/event/EventController.java
  Microservices/event-service/src/main/java/app/sportahub/eventservice/exception/event/InvalidEventCoordinatesReceivedException.java
  Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventService.java
  Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java
  Microservices/event-service/src/test/java/app/sportahub/eventservice/controller/event/EventControllerTest.java
  Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventSearchTest.java
  Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
Labels: backend, pull request

#450 GH-0: [refactor] Fix Failing Test Suites
  Microservices/user-service/src/test/java/app/sportahub/userservice/controller/user/UserControllerTest.java
  Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Labels: backend, pull request

#449 GH-0: [hotfix] adding the api.sportahub.app endpoint to config files
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/config/OpenApiConfig.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/config/WebSocketConfig.java
  Microservices/messaging-service/src/main/resources/application.properties
Labels: backend, pull request
