Repository SOEN490-SportsApp/SportsApp, pull requests merged in 2025-01, with the labels that each got.

#226 GH-225: [fix] Allow patch and head operations through Swagger
  Microservices/event-service/src/main/java/app/sportahub/eventservice/config/WebConfig.java
  Microservices/user-service/src/main/java/app/sportahub/userservice/config/auth/WebConfig.java
Labels: backend, pull request

#235 GH-208: [feat] Added functionality to delete users
  Microservices/user-service/src/main/java/app/sportahub/userservice/controller/user/UserController.java
  Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserService.java
  Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java
  Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Labels: backend, pull request

#257 GH-0: [fix] Removed unnecessary failing test
  Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserServiceTest.java
Labels: backend, pull request

#265 GH-253: [ci] Update CI Workflow for Dynamic Microservice Builds and Deployment
  .github/workflows/build-deploy-microservices.yaml
Labels: pull request, setup

#258 GH-256: [fix] Last event display profile
  ClientApp/app/(tabs)/home/index.tsx
  ClientApp/app/_layout.tsx
  ClientApp/components/Event/EventListProfilePage.tsx
Labels: bug, frontend, pull request

#270 [fix]: Add permissions to build-deploy-microservices.yaml
  .github/workflows/build-deploy-microservices.yaml
Labels: backend, pull request

#275 [feat] Add Release 2 Video to the README
  README.md
Labels: pull request

#281 GH-280: [fix] Fix event creation cutoff time and minor UI improvements
  ClientApp/app/(tabs)/create/index.tsx
  ClientApp/app/(tabs)/profile/index.tsx
  ClientApp/components/Helper Components/FriendCard.tsx
Labels: frontend

#283 [refactor] add creator to event participants
  Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java
Labels: backend, pull request
