Repository SOEN490-SportsApp/SportsApp, pull requests merged in 2025-02, with the labels that each got.

#293 GH-292: [fix] Fix participant list update
  ClientApp/app/events/[eventId].tsx
Labels: bug, frontend, Event Managment, pull request

#296 GH-0: [fix] fixed type in endpoint for retrieving events participated in by a user
  Microservices/event-service/src/main/java/app/sportahub/eventservice/controller/EventController.java
Labels: bug, backend, pull request

#304 GH-0: [fix] Fix GitHub Access Token Permission Issue
  .github/workflows/email-service-ci-cd.yml
  .github/workflows/event-service-ci-cd.yml
  .github/workflows/frontend-ci-cd.yml
  .github/workflows/gateway-service-ci-cd.yml
  .github/workflows/user-service-ci-cd.yml
Labels: bug, pull request

#305 GH-212: [fix] Fix Permission issue in CI/CD Controller
  .github/workflows/ci-cd-controller.yml
Labels: pull request

#308 GH-0: [refactor] Return Correct Response In User Search Endpoint.
  Microservices/user-service/src/main/java/app/sportahub/userservice/service/user/UserServiceImpl.java
  Microservices/user-service/src/test/java/app/sportahub/userservice/service/user/UserSearchTest.java
Labels: pull request

#311 GH-276: [feat] User can now delete the account
  ClientApp/app/(tabs)/profile/(settings)/_layout.tsx
  ClientApp/app/(tabs)/profile/(settings)/deleteAccountPage.tsx
  ClientApp/app/(tabs)/profile/(settings)/settingsPage.tsx
  ClientApp/services/authService.ts
Labels: frontend

#324 fix: Add Execute Permission to gradlew
  Microservices/messaging-service/gradlew
Labels: backend, pull request

#325 fix: Add Missing Gradle Wrapper
  Microservices/messaging-service/gradle/wrapper/gradle-wrapper.jar
  Microservices/messaging-service/gradle/wrapper/gradle-wrapper.properties
Labels: backend, pull request

#318 GH-317: [fix] Fix Microservice Image Build
  .github/workflows/build-deploy-microservices.yaml
Labels: backend, pull request

#329 GH-0: [chore] Changing jdk version to Java 21 for storage service
  Microservices/storage-service/build.gradle
Labels: backend, setup

#341 GH-0: [feat] Fix Failing Test and Update leaveEvent Logic
  Microservices/event-service/src/main/java/app/sportahub/eventservice/service/event/EventServiceImpl.java
  Microservices/event-service/src/test/java/app/sportahub/eventservice/service/event/EventServiceTest.java
Labels: backend, pull request

#348 GH-0: [test] Fix failing test for post service
  Microservices/event-service/src/test/java/app/sportahub/eventservice/service/social/PostServiceImplTest.java
Labels: backend, pull request

#355 GH-354: [fix] Back navigation from profile fix
  ClientApp/__tests__/userProfiles/id.test.tsx
  ClientApp/app/_layout.tsx
  ClientApp/app/events/[eventId].tsx
  ClientApp/app/userProfiles/[id].tsx
  ClientApp/app/userProfiles/_layout.tsx
  ClientApp/components/Helper Components/FriendCard.tsx
  ClientApp/components/Profile/FriendCardProfilePage.tsx
  ClientApp/utils/Deeplinks/Deeplinks.ts
Labels: frontend, pull request
