Repository SOEN490-SportsApp/SportsApp, pull requests merged in 2025-04, with the labels that each got.

#462 GH-0: [hotfix] added new Member object to MessageRequest/MessageResponse
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/dto/request/message/MessageRequest.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/dto/response/message/MessageResponse.java
  Microservices/messaging-service/src/test/java/app/sportahub/messaging_service/service/MessagingServiceTest.java
Labels: backend, pull request

#463 GH-0: [hotfix] added new senderImage field to Message/MessageRequest/MessageResponse
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/dto/request/message/MessageRequest.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/dto/response/message/MessageResponse.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/mapper/MessageMapper.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/model/Message.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/service/MessagingService.java
  Microservices/messaging-service/src/main/java/app/sportahub/messagingservice/service/MessagingServiceImpl.java
  Microservices/messaging-service/src/test/java/app/sportahub/messaging_service/service/MessagingServiceTest.java
Labels: backend, pull request

#468 [fix] Update SecurityConfig to allow access to actuator endpoints
  Microservices/notification-service/src/main/java/app/sportahub/notificationservice/config/auth/SecurityConfig.java
Labels: backend, pull request

#469 [fix] Remove Redundant KafkaTemplate Bean Method
  Microservices/event-service/src/main/java/app/sportahub/eventservice/config/kafka/KafkaProducerConfig.java
Labels: backend, pull request

#473 GH-382: [fix] Update kafka-events dependency version to 1.0.8
  Microservices/event-service/build.gradle
  Microservices/notification-service/build.gradle
  Microservices/orchestration-service/build.gradle
  Microservices/user-service/build.gradle
  libs/kafka-events/build.gradle
Labels: backend

#478 GH-0: [fix] updated kafka events library version to 1.0.9
  Microservices/email-service/build.gradle
  Microservices/event-service/build.gradle
  Microservices/notification-service/build.gradle
  Microservices/orchestration-service/build.gradle
  Microservices/user-service/build.gradle
Labels: bug

#477 Improving readme structure
  README.md
Labels: documentation
